services:
  db:
    image: postgres:15
    container_name: zooavito-db
    environment:
      POSTGRES_DB: ${DB_POSTGRES_DATABASE}
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - zooavito-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: zooavito-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      GOOGLE_RECAPTCHA_SECRET: ${GOOGLE_RECAPTCHA_SECRET}
      APP_CORS_ALLOWED_ORIGINS: ${APP_CORS_ALLOWED_ORIGINS}
    dns:
      - 8.8.8.8
      - 8.8.4.4
    depends_on:
      db:
        condition: service_healthy
    networks:
      - zooavito-network
    restart: on-failure

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_RECAPTCHA_SITE_KEY=${REACT_APP_RECAPTCHA_SITE_KEY}
    container_name: zooavito-frontend
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_RECAPTCHA_SITE_KEY=${REACT_APP_RECAPTCHA_SITE_KEY}
    depends_on:
      - backend
    networks:
      - zooavito-network
    restart: unless-stopped

networks:
  zooavito-network:
    driver: bridge

volumes:
  postgres_data: